# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.4 on 2016-12-14 21:26
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.10 on 2016-12-14 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
>>>>>>> 66e2efd558275a9e996b695afa052b8c89cf1701


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
<<<<<<< HEAD
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
=======
                ('email', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('um', django.db.models.manager.Manager()),
>>>>>>> 66e2efd558275a9e996b695afa052b8c89cf1701
            ],
        ),
    ]
